name: Go

on:
  push:
    branches: [ v1 ]
  pull_request:
    branches: [ v1 ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        FS_HOST: ${{ secrets.FS_HOST }}
        FS_PORT: ${{ secrets.FS_PORT }}
        FS_ESLPASS: ${{ secrets.FS_ESLPASS }}
      run: go test -v ./...
